# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy local code to the container image.
COPY . /app

# Install pip dependencies
RUN pip install --upgrade pip \
    && pip install .

# Expose necessary port if any (MCP typically uses stdio, but if needed, uncomment below)
# EXPOSE 8000

# Run the MCP Server
CMD ["python", "src/main.py"]
