# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.13-slim

# Set working directory
WORKDIR /app

# Copy local code to the container image.
COPY . /app

# Install pip dependencies
RUN pip install --upgrade pip \
    && pip install .

# Default environment variables
ENV REDIS_HOST=127.0.0.1 \
    REDIS_PORT=6379 \
    REDIS_CLUSTER_MODE=false \
    REDIS_CLUSTER_NODES=""

# Expose the MCP server port
EXPOSE 3333

# Run the MCP Server
CMD ["python", "src/main.py"]
